/* eslint-disable no-console */
import { writeFileSync, mkdirSync } from 'fs';
import { dirname, resolve } from 'path';
import $RefParser from '@apidevtools/json-schema-ref-parser';
import { compile } from 'json-schema-to-typescript';

// Pinned to a core commit that includes the `schemaVersion` envelope field.
// Bump deliberately (to a tag once cut); the CI drift guard fails if the
// committed outputs no longer match this source.
const SCHEMA_SOURCE_URL =
  process.env.REGIS_SCHEMA_SOURCE ??
  'https://raw.githubusercontent.com/trivoallan/regis/ec31f8fd497301da8bdee1521768591034a539fd/regis/schemas/report/report.schema.json';

const SCHEMA_OUT = resolve(__dirname, '../src/schema/report.schema.json');
const TYPES_OUT = resolve(__dirname, '../src/types.ts');

async function main(): Promise<void> {
  // Resolve the one external $ref (../playbook/result.schema.json) into a
  // self-contained schema Ajv can compile without network access at runtime.
  const bundled = await $RefParser.bundle(SCHEMA_SOURCE_URL);

  mkdirSync(dirname(SCHEMA_OUT), { recursive: true });
  writeFileSync(SCHEMA_OUT, `${JSON.stringify(bundled, null, 2)}\n`);

  const ts = await compile(bundled as object, 'Report', {
    bannerComment:
      '/* eslint-disable */\n/**\n * AUTO-GENERATED by scripts/sync-contract.ts.\n * Do not edit by hand — run `yarn generate:contract`.\n */',
    additionalProperties: false,
  });
  writeFileSync(TYPES_OUT, ts);

  console.log(`Wrote:\n  ${SCHEMA_OUT}\n  ${TYPES_OUT}`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
