import { readdirSync, readFileSync } from 'fs';
import { resolve } from 'path';
import { validateReport } from './validate';

// Guards the demo dataset shipped under examples/ (generated by
// examples/regis-dataset.cjs). The backend validates these reports at fetch
// time, and PostureSummary reads playbooks[0].playbook_name for attribution —
// so every generated report must be schema-valid AND carry a playbook.
const REPORTS_DIR = resolve(__dirname, '../../../examples/reports');
const KNOWN_PLAYBOOKS = ['default', 'pci-dss'];

const reportFiles = readdirSync(REPORTS_DIR).filter(f => f.endsWith('.json'));

describe('examples/reports', () => {
  it('ships at least one report', () => {
    expect(reportFiles.length).toBeGreaterThan(0);
  });

  it.each(reportFiles)('%s validates against the report schema', file => {
    const raw = JSON.parse(readFileSync(resolve(REPORTS_DIR, file), 'utf8'));
    expect(() => validateReport(raw)).not.toThrow();
  });

  it.each(reportFiles)('%s carries playbook attribution', file => {
    const report = validateReport(
      JSON.parse(readFileSync(resolve(REPORTS_DIR, file), 'utf8')),
    );
    const name = report.playbooks?.[0]?.playbook_name;
    expect(name).toBeTruthy();
    expect(KNOWN_PLAYBOOKS).toContain(name);
  });
});
