/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/sync-contract.ts.
 * Do not edit by hand — run `yarn generate:contract`.
 */

/**
 * Final report envelope produced by regis, containing request metadata and analyzer results.
 */
export interface Report {
  /**
   * Report-structure contract version. Consumers (e.g. the standalone dashboard) gate rendering on this. Distinct from `version` (package/snapshot).
   */
  schemaVersion: number;
  /**
   * Version of regis that generated this report.
   */
  version: string | null;
  /**
   * ISO 8601 date when this version was snapshotted in the doc site.
   */
  snapshot_date?: string;
  /**
   * The earned tier (e.g. Gold, Silver, Bronze) based on playbook conditions.
   */
  tier?: string | null;
  badges?: {
    /**
     * Unique identifier for the badge.
     */
    slug?: string;
    /**
     * Domain of the badge (e.g., 'security', 'hygiene').
     */
    scope: string;
    /**
     * Display value or grade (e.g., 'A', '95%').
     */
    value?: string | null;
    /**
     * Visual style indicator.
     */
    class: "success" | "warning" | "error" | "information";
    /**
     * The full label string (scope or scope: value).
     */
    label?: string;
  }[];
  /**
   * Arbitrary user-provided metadata.
   */
  metadata?: {
    [k: string]: unknown;
  };
  /**
   * Custom templated links.
   */
  links?: {
    /**
     * Display label for the link.
     */
    label: string;
    /**
     * Target URL.
     */
    url: string;
  }[];
  /**
   * Metadata describing the analysis request.
   */
  request: {
    /**
     * Original URL or image reference provided by the user.
     */
    url: string;
    /**
     * Resolved registry hostname (e.g. registry-1.docker.io).
     */
    registry: string;
    /**
     * Full repository path (e.g. library/nginx).
     */
    repository: string;
    /**
     * Image tag that was analyzed.
     */
    tag: string;
    /**
     * Resolved image manifest digest (e.g. sha256-xxx), if available.
     */
    digest?: string | null;
    /**
     * List of analyzer names that were executed.
     */
    analyzers: string[];
    /**
     * ISO 8601 UTC timestamp of the analysis.
     */
    timestamp: string;
    /**
     * Arbitrary user-provided metadata.
     */
    metadata?: {
      [k: string]: unknown;
    };
  };
  /**
   * Analyzer results keyed by analyzer name.
   */
  results: {
    [k: string]: {};
  };
  /**
   * List of evaluated playbook results.
   */
  playbooks?: PlaybookResult[];
  playbook?: PlaybookResult1;
  /**
   * List of unified rule results (promoted from playbooks[0]).
   */
  rules?: {
    /**
     * Unique identifier for the rule.
     */
    slug: string;
    /**
     * Human-readable name of the rule.
     */
    description: string;
    /**
     * Priority level (Gold, Silver, Bronze).
     */
    level?: string;
    /**
     * Associated metadata tags.
     */
    tags?: string[];
    /**
     * Whether the rule criteria were met.
     */
    passed: boolean;
    /**
     * Detailed execution status.
     */
    status: "passed" | "failed" | "incomplete";
    /**
     * Reasoning or details for the rule result.
     */
    message: string;
    /**
     * List of analyzers that contributed data to this rule.
     */
    analyzers?: string[];
  }[];
  /**
   * Summary of rule evaluation results.
   */
  rules_summary?: {
    score?: number;
    total?: string[];
    passed?: string[];
    by_tag?: {
      [k: string]: {
        /**
         * List of rule slugs in this group.
         */
        rules: string[];
        /**
         * List of slugs for rules that passed.
         */
        passed_rules: string[];
        /**
         * Percentage score for this group.
         */
        score: number;
      };
    };
  };
}
/**
 * Final playbook result produced by regis, containing metadata and analyzer results.
 */
export interface PlaybookResult {
  /**
   * Identifier of the playbook that was executed.
   */
  playbook_name: string;
  /**
   * SemVer of the playbook that produced this report.
   */
  playbook_version?: string | null;
  /**
   * schemaVersion of the playbook format that produced this report.
   */
  schema_version?: number | null;
  /**
   * Sidebar navigation metadata for the report UI.
   */
  sidebar?: {};
  /**
   * Version of regis that generated this report.
   */
  version?: string | null;
  /**
   * The earned tier (e.g. Gold, Silver, Bronze) based on playbook conditions.
   */
  tier?: string | null;
  badges?: {
    /**
     * Unique identifier for the badge.
     */
    slug?: string;
    /**
     * Domain of the badge (e.g., 'security', 'hygiene').
     */
    scope: string;
    /**
     * Display value or grade (e.g., 'A', '95%').
     */
    value?: string | null;
    /**
     * Visual style indicator.
     */
    class: "success" | "warning" | "error" | "information";
    /**
     * The full label string (scope or scope: value).
     */
    label?: string;
  }[];
  rules?: {
    /**
     * Unique identifier for the rule.
     */
    slug: string;
    /**
     * Human-readable name of the rule.
     */
    description: string;
    /**
     * Priority level (Gold, Silver, Bronze).
     */
    level?: string;
    /**
     * Associated metadata tags.
     */
    tags?: string[];
    /**
     * Whether the rule criteria were met.
     */
    passed: boolean;
    /**
     * Detailed execution status.
     */
    status: "passed" | "failed" | "incomplete";
    /**
     * Reasoning or details for the rule result.
     */
    message: string;
    /**
     * List of analyzers that contributed data to this rule.
     */
    analyzers?: string[];
  }[];
  rules_summary?: {
    score: number;
    total: string[];
    passed: string[];
    by_tag?: {
      [k: string]: {
        rules: string[];
        passed_rules: string[];
        score: number;
      };
    };
  };
  /**
   * Overall percentage score for the playbook.
   */
  score: number;
  /**
   * Total number of scorecards evaluated.
   */
  total_scorecards: number;
  /**
   * Number of scorecards that passed.
   */
  passed_scorecards: number;
  /**
   * External links associated with this playbook result.
   */
  links?: {
    /**
     * Display label for the link.
     */
    label: string;
    /**
     * Target URL.
     */
    url: string;
  }[];
  pages: {
    /**
     * Page title.
     */
    title: string;
    /**
     * URL-friendly identifier for the page.
     */
    slug?: string | null;
    /**
     * Percentage score for this page.
     */
    score: number;
    /**
     * Total scorecards on this page.
     */
    total_scorecards: number;
    /**
     * Passed scorecards on this page.
     */
    passed_scorecards: number;
    /**
     * @minItems 1
     */
    sections: [
      {
        /**
         * Section name.
         */
        name: string;
        /**
         * Informative text for the section.
         */
        hint?: string;
        /**
         * Percentage score for this section.
         */
        score: number;
        /**
         * Total scorecards in this section.
         */
        total_scorecards: number;
        /**
         * Passed scorecards in this section.
         */
        passed_scorecards: number;
        levels_summary?: {
          [k: string]: {
            total: number;
            passed: number;
            percentage: number;
          };
        };
        tags_summary?: {
          [k: string]: {
            total: number;
            passed: number;
            percentage: number;
          };
        };
        scorecards: {
          /**
           * Unique scorecard identifier.
           */
          name: string;
          /**
           * Display description.
           */
          description: string;
          /**
           * Assigned severity level name.
           */
          level?: string | null;
          /**
           * Associated search tags.
           */
          tags?: string[];
          /**
           * Analyzers used for this scorecard.
           */
          analyzers?: string[];
          /**
           * True if condition was met.
           */
          passed: boolean;
          /**
           * Execution status.
           */
          status?: "passed" | "failed" | "incomplete";
          /**
           * The JsonLogic expression evaluated.
           */
          condition?: string;
          /**
           * Detailed explanation of calculated result.
           */
          details?: string;
        }[];
        display?: {
          analyzers?: string[];
          widgets?: {
            /**
             * Widget display label.
             */
            label?: string;
            /**
             * Data resolution path.
             */
            value?: string;
            /**
             * Icon identifier or emoji.
             */
            icon?: string;
            /**
             * The actual value fetched after resolution.
             */
            resolved_value?: {
              [k: string]: unknown;
            };
          }[];
        };
      },
      ...{
        /**
         * Section name.
         */
        name: string;
        /**
         * Informative text for the section.
         */
        hint?: string;
        /**
         * Percentage score for this section.
         */
        score: number;
        /**
         * Total scorecards in this section.
         */
        total_scorecards: number;
        /**
         * Passed scorecards in this section.
         */
        passed_scorecards: number;
        levels_summary?: {
          [k: string]: {
            total: number;
            passed: number;
            percentage: number;
          };
        };
        tags_summary?: {
          [k: string]: {
            total: number;
            passed: number;
            percentage: number;
          };
        };
        scorecards: {
          /**
           * Unique scorecard identifier.
           */
          name: string;
          /**
           * Display description.
           */
          description: string;
          /**
           * Assigned severity level name.
           */
          level?: string | null;
          /**
           * Associated search tags.
           */
          tags?: string[];
          /**
           * Analyzers used for this scorecard.
           */
          analyzers?: string[];
          /**
           * True if condition was met.
           */
          passed: boolean;
          /**
           * Execution status.
           */
          status?: "passed" | "failed" | "incomplete";
          /**
           * The JsonLogic expression evaluated.
           */
          condition?: string;
          /**
           * Detailed explanation of calculated result.
           */
          details?: string;
        }[];
        display?: {
          analyzers?: string[];
          widgets?: {
            /**
             * Widget display label.
             */
            label?: string;
            /**
             * Data resolution path.
             */
            value?: string;
            /**
             * Icon identifier or emoji.
             */
            icon?: string;
            /**
             * The actual value fetched after resolution.
             */
            resolved_value?: {
              [k: string]: unknown;
            };
          }[];
        };
      }[]
    ];
  }[];
  /**
   * Cookiecutter templates to be run for MR descriptions.
   */
  mr_templates?: {
    url: string;
    directory?: string;
  }[];
}
/**
 * Primary playbook result (shorthand for playbooks[0]).
 */
export interface PlaybookResult1 {
  /**
   * Identifier of the playbook that was executed.
   */
  playbook_name: string;
  /**
   * SemVer of the playbook that produced this report.
   */
  playbook_version?: string | null;
  /**
   * schemaVersion of the playbook format that produced this report.
   */
  schema_version?: number | null;
  /**
   * Sidebar navigation metadata for the report UI.
   */
  sidebar?: {};
  /**
   * Version of regis that generated this report.
   */
  version?: string | null;
  /**
   * The earned tier (e.g. Gold, Silver, Bronze) based on playbook conditions.
   */
  tier?: string | null;
  badges?: {
    /**
     * Unique identifier for the badge.
     */
    slug?: string;
    /**
     * Domain of the badge (e.g., 'security', 'hygiene').
     */
    scope: string;
    /**
     * Display value or grade (e.g., 'A', '95%').
     */
    value?: string | null;
    /**
     * Visual style indicator.
     */
    class: "success" | "warning" | "error" | "information";
    /**
     * The full label string (scope or scope: value).
     */
    label?: string;
  }[];
  rules?: {
    /**
     * Unique identifier for the rule.
     */
    slug: string;
    /**
     * Human-readable name of the rule.
     */
    description: string;
    /**
     * Priority level (Gold, Silver, Bronze).
     */
    level?: string;
    /**
     * Associated metadata tags.
     */
    tags?: string[];
    /**
     * Whether the rule criteria were met.
     */
    passed: boolean;
    /**
     * Detailed execution status.
     */
    status: "passed" | "failed" | "incomplete";
    /**
     * Reasoning or details for the rule result.
     */
    message: string;
    /**
     * List of analyzers that contributed data to this rule.
     */
    analyzers?: string[];
  }[];
  rules_summary?: {
    score: number;
    total: string[];
    passed: string[];
    by_tag?: {
      [k: string]: {
        rules: string[];
        passed_rules: string[];
        score: number;
      };
    };
  };
  /**
   * Overall percentage score for the playbook.
   */
  score: number;
  /**
   * Total number of scorecards evaluated.
   */
  total_scorecards: number;
  /**
   * Number of scorecards that passed.
   */
  passed_scorecards: number;
  /**
   * External links associated with this playbook result.
   */
  links?: {
    /**
     * Display label for the link.
     */
    label: string;
    /**
     * Target URL.
     */
    url: string;
  }[];
  pages: {
    /**
     * Page title.
     */
    title: string;
    /**
     * URL-friendly identifier for the page.
     */
    slug?: string | null;
    /**
     * Percentage score for this page.
     */
    score: number;
    /**
     * Total scorecards on this page.
     */
    total_scorecards: number;
    /**
     * Passed scorecards on this page.
     */
    passed_scorecards: number;
    /**
     * @minItems 1
     */
    sections: [
      {
        /**
         * Section name.
         */
        name: string;
        /**
         * Informative text for the section.
         */
        hint?: string;
        /**
         * Percentage score for this section.
         */
        score: number;
        /**
         * Total scorecards in this section.
         */
        total_scorecards: number;
        /**
         * Passed scorecards in this section.
         */
        passed_scorecards: number;
        levels_summary?: {
          [k: string]: {
            total: number;
            passed: number;
            percentage: number;
          };
        };
        tags_summary?: {
          [k: string]: {
            total: number;
            passed: number;
            percentage: number;
          };
        };
        scorecards: {
          /**
           * Unique scorecard identifier.
           */
          name: string;
          /**
           * Display description.
           */
          description: string;
          /**
           * Assigned severity level name.
           */
          level?: string | null;
          /**
           * Associated search tags.
           */
          tags?: string[];
          /**
           * Analyzers used for this scorecard.
           */
          analyzers?: string[];
          /**
           * True if condition was met.
           */
          passed: boolean;
          /**
           * Execution status.
           */
          status?: "passed" | "failed" | "incomplete";
          /**
           * The JsonLogic expression evaluated.
           */
          condition?: string;
          /**
           * Detailed explanation of calculated result.
           */
          details?: string;
        }[];
        display?: {
          analyzers?: string[];
          widgets?: {
            /**
             * Widget display label.
             */
            label?: string;
            /**
             * Data resolution path.
             */
            value?: string;
            /**
             * Icon identifier or emoji.
             */
            icon?: string;
            /**
             * The actual value fetched after resolution.
             */
            resolved_value?: {
              [k: string]: unknown;
            };
          }[];
        };
      },
      ...{
        /**
         * Section name.
         */
        name: string;
        /**
         * Informative text for the section.
         */
        hint?: string;
        /**
         * Percentage score for this section.
         */
        score: number;
        /**
         * Total scorecards in this section.
         */
        total_scorecards: number;
        /**
         * Passed scorecards in this section.
         */
        passed_scorecards: number;
        levels_summary?: {
          [k: string]: {
            total: number;
            passed: number;
            percentage: number;
          };
        };
        tags_summary?: {
          [k: string]: {
            total: number;
            passed: number;
            percentage: number;
          };
        };
        scorecards: {
          /**
           * Unique scorecard identifier.
           */
          name: string;
          /**
           * Display description.
           */
          description: string;
          /**
           * Assigned severity level name.
           */
          level?: string | null;
          /**
           * Associated search tags.
           */
          tags?: string[];
          /**
           * Analyzers used for this scorecard.
           */
          analyzers?: string[];
          /**
           * True if condition was met.
           */
          passed: boolean;
          /**
           * Execution status.
           */
          status?: "passed" | "failed" | "incomplete";
          /**
           * The JsonLogic expression evaluated.
           */
          condition?: string;
          /**
           * Detailed explanation of calculated result.
           */
          details?: string;
        }[];
        display?: {
          analyzers?: string[];
          widgets?: {
            /**
             * Widget display label.
             */
            label?: string;
            /**
             * Data resolution path.
             */
            value?: string;
            /**
             * Icon identifier or emoji.
             */
            icon?: string;
            /**
             * The actual value fetched after resolution.
             */
            resolved_value?: {
              [k: string]: unknown;
            };
          }[];
        };
      }[]
    ];
  }[];
  /**
   * Cookiecutter templates to be run for MR descriptions.
   */
  mr_templates?: {
    url: string;
    directory?: string;
  }[];
}
